import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import AuthSessionProvider from './components/AuthSessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} w-full min-h-dvh flex flex-col container mx-auto`}>
        <AuthSessionProvider>
          <Navbar />
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
